"""Frozen-grid, feasibility, provenance, dispatch, and launcher tests for
the A6 holdout execution path.  Solver calls are stubbed; no holdout method
outcomes are generated by this battery."""
from __future__ import annotations

import copy
import json
import os
from pathlib import Path
import subprocess
import sys
from types import SimpleNamespace

import pytest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import experiments.run_a6_holdout as holdout
import experiments.run_b2a2_pilot as dictator_driver
from egglab import checkpoint
from egglab.instance import synthetic_instance
from egglab.market import make_affine_market


def test_frozen_grid_is_exact_128_matched_cells():
    cells = holdout.build_cells()
    holdout.validate_grid(cells)
    assert len(cells) == len(set(cells)) == 128
    assert {c[0] for c in cells} == {"a2", "a6_a4"}
    assert all(c[0] != "a6_a3" for c in cells)
    assert {c[1] for c in cells} == set(range(16, 32))
    assert {c[2] for c in cells} == {8, 12}
    assert {c[3] for c in cells} == {0.01, 0.05}
    assert sum(c[0] == "a2" for c in cells) == 64
    assert sum(c[0] == "a6_a4" for c in cells) == 64
    pairs = {(c[1], c[2], c[3]) for c in cells}
    assert len(pairs) == 64
    assert all(
        sum((c[1], c[2], c[3]) == key for c in cells) == 2
        for key in pairs
    )
    assert holdout.EPSILON == 1e-2 and holdout.BUDGET == 240


def test_grid_rejects_drift_duplicate_and_a6_a3():
    cells = holdout.build_cells()
    for bad in (
        cells[:-1],
        cells[:-1] + [cells[0]],
        [("a6_a3", *c[1:]) if i == 0 else c
         for i, c in enumerate(cells)],
        [(c[0], 15, *c[2:]) if i == 0 else c
         for i, c in enumerate(cells)],
    ):
        with pytest.raises(holdout.HoldoutGuardError):
            holdout.validate_grid(bad)


def test_canonical_selection_is_committed_exact_and_reproduces_rule():
    selection = holdout.load_committed_selection()
    assert selection["sha256"] == holdout.EXPECTED_SELECTION_SHA256
    assert selection["selected_arm"] == "a6_a4"
    assert selection["a6_a3_wins"] == 2
    assert selection["win_threshold"] == 9
    assert selection["artifact_commit"] == holdout.SELECTION_GATE_COMMIT
    assert selection["analysis_code_commit"].startswith("c663fcf")


def test_selection_rejects_wrong_hash_and_internal_decision():
    path = holdout.REPO_DIR / holdout.SELECTION_RELATIVE_PATH
    payload = json.loads(path.read_text())
    with pytest.raises(holdout.HoldoutGuardError, match="SHA-256"):
        holdout._validate_selection_payload(
            payload, "0" * 64
        )
    changed = copy.deepcopy(payload)
    changed["selected_arm"] = "a6_a3"
    with pytest.raises(holdout.HoldoutGuardError, match="frozen decision"):
        holdout._validate_selection_payload(
            changed, holdout.EXPECTED_SELECTION_SHA256
        )
    changed = copy.deepcopy(payload)
    changed["matched"][0]["a6_a3_wins"] = not changed["matched"][0][
        "a6_a3_wins"
    ]
    with pytest.raises(holdout.HoldoutGuardError, match="reproduce"):
        holdout._validate_selection_payload(
            changed, holdout.EXPECTED_SELECTION_SHA256
        )


def test_whole_population_has_deterministic_exact_zero_charge_covers():
    selection = holdout.load_committed_selection()
    a = holdout.build_feasibility_manifest(selection, "code-commit-test")
    b = holdout.build_feasibility_manifest(selection, "code-commit-test")
    assert a == b
    assert a["schema"] == holdout.PREFLIGHT_SCHEMA
    assert len(a["physical_instances"]) == 32
    assert len(a["markets"]) == 64
    assert a["grid"]["method_cells"] == 128
    for row in a["physical_instances"]:
        assert row["replay_ok"] is True
        assert row["required_vehicles"] == row["n_trips"] // 2
        assert row["required_vehicles"] <= row["max_vehicles"]
        covered = [tid for pair in row["pairs"] for tid in pair["trip_ids"]]
        assert len(covered) == len(set(covered)) == row["n_trips"]
        assert all(pair["arc_kind"] in ("dir", "dep")
                   for pair in row["pairs"])
        assert all(
            stage["soc_kwh"] >= stage["required_min_kwh"]
            for pair in row["pairs"]
            for stage in pair["soc_trace_kwh"]
        )


def test_constructive_gate_fails_loudly_when_vehicle_limit_precludes_cover():
    inst = synthetic_instance(seed=16, n_trips=8)
    inst.max_vehicles = 3
    with pytest.raises(holdout.HoldoutGuardError, match="needs 4 vehicles"):
        holdout.constructive_zero_charge_cover(inst)


def test_preflight_is_atomic_deterministic_and_tamper_refusing(tmp_path):
    selection = holdout.load_committed_selection()
    root = str(tmp_path / "runs")
    first = holdout.write_preflight(root, selection, "code-test")
    path = tmp_path / "runs" / holdout.PREFLIGHT_FILENAME
    assert json.loads(path.read_text()) == first
    second = holdout.write_preflight(root, selection, "code-test")
    assert second == first
    observed, digest = holdout.load_valid_preflight(
        root, selection, "code-test"
    )
    assert observed == first and len(digest) == 64
    tampered = copy.deepcopy(first)
    tampered["physical_instances"].pop()
    checkpoint.save(str(path), tampered)
    with pytest.raises(holdout.HoldoutGuardError, match="tampered"):
        holdout.load_valid_preflight(root, selection, "code-test")


def test_missing_preflight_refuses_before_method_output(tmp_path):
    selection = holdout.load_committed_selection()
    root = str(tmp_path / "runs")
    with pytest.raises(holdout.HoldoutGuardError, match="before either"):
        holdout.load_valid_preflight(root, selection, "code-test")
    assert not (tmp_path / "runs").exists()


def _fake_state(kind="budget_exhausted"):
    return {
        "oracle_calls": 240,
        "outcome": {
            "type": kind,
            "gap": 0.2,
            "oracle_calls_clean": 49,
            "oracle_calls_stab": 191,
            "uplift_interval": [0.0, 1.0],
        },
    }


def test_dispatches_fresh_a2_and_a6_a4_with_truthful_lineage(
    tmp_path, monkeypatch
):
    selection = holdout.load_committed_selection()
    gate = {
        "selection": selection,
        "code_commit": "implementation-commit",
        "preflight_sha256": "f" * 64,
    }
    args = SimpleNamespace(out=str(tmp_path), mip_gap=1e-6)
    dictator_calls = []
    a2_calls = []
    a6_calls = []

    def fake_dictator(inst, market, out, tag, cell, kw, *, experiment):
        dictator_calls.append((tag, tuple(cell), experiment))
        return {"z_d_ub": 1.0, "tol_d": 1e-2}

    monkeypatch.setattr(holdout, "_dictator_stage", fake_dictator)
    monkeypatch.setattr(
        holdout, "certified_cg",
        lambda *a, **kw: a2_calls.append(kw) or _fake_state(),
    )
    monkeypatch.setattr(
        holdout, "certified_cg_a6",
        lambda *a, **kw: a6_calls.append(kw) or _fake_state(),
    )

    a2 = ("a2", 16, 8, 0.01)
    a6 = ("a6_a4", 16, 8, 0.01)
    # A valid budget-exhausted outcome returns normally: certification is an
    # endpoint, not a per-cell completeness exception.
    holdout.run_cell(a2, args, gate=gate)
    holdout.run_cell(a6, args, gate=gate)

    assert [c[2] for c in dictator_calls] == ["a6-holdout", "a6-holdout"]
    assert a2_calls[0]["method"] == "a2"
    assert a2_calls[0]["experiment"] == "a6-holdout"
    assert a6_calls[0]["method"] == "a6_a4"
    assert a6_calls[0]["experiment"] == "a6-holdout"
    assert not any(kw.get("method") == "a6_a3" for kw in a6_calls)
    for cell in (a2, a6):
        p = tmp_path / holdout._cell_tag(cell) / \
            holdout.CELL_PROVENANCE_FILENAME
        x = json.loads(p.read_text())
        assert x["campaign"] == "a6-holdout"
        assert x["preflight_sha256"] == "f" * 64
        assert x["selection"]["selected_arm"] == "a6_a4"


def test_dictator_helper_labels_record_and_versions_representation_identity(
    tmp_path, monkeypatch
):
    """Campaign lineage and representation policy are both checkpointed."""
    inst = synthetic_instance(seed=16, n_trips=8)
    market = make_affine_market(inst, shape="duck", b_scale=0.01)
    stats = SimpleNamespace(
        extra={"adaptive_converged": True, "adaptive_gap_abs": 0.0,
               "adaptive_tol_abs": 1e-2, "adaptive_lb": 1.0},
        status="OPTIMAL", bound=0.0,
    )
    sol = SimpleNamespace(
        stats=stats, obj_true=1.0, obj_model=1.0, ops_cost=1.0,
        load=[0.0] * inst.n_slots, charges=[], energy_charged_kwh=0.0)
    seen = {}
    monkeypatch.setattr(dictator_driver, "backend", lambda: "GRB")
    monkeypatch.setattr(
        dictator_driver, "solve_dictator", lambda *a, **kw: sol
    )

    def fake_record(experiment, *args, **kwargs):
        seen["experiment"] = experiment
        return {"replay_ok": True, "experiment": experiment}

    monkeypatch.setattr(dictator_driver, "make_record", fake_record)
    state = dictator_driver._dictator_stage(
        inst, market, str(tmp_path), "tag", ["a2", 16, 8, 0.01],
        {"max_mip_gap": 1e-6, "time_limit_s": None},
        experiment="a6-holdout",
    )
    assert seen["experiment"] == "a6-holdout"
    assert state["record"]["experiment"] == "a6-holdout"
    assert "experiment" not in state["identity"]
    assert state["identity"]["load_reconstruction"] == {
        "policy_version": 1,
        "tolerance_kwh": pytest.approx(1e-4),
    }
    with pytest.raises(RuntimeError, match="record experiment"):
        dictator_driver._dictator_stage(
            inst, market, str(tmp_path), "tag",
            ["a2", 16, 8, 0.01],
            {"max_mip_gap": 1e-6, "time_limit_s": None},
            experiment="b2a2-pilot",
        )


def test_cell_provenance_rejects_stale_resume(tmp_path):
    selection = holdout.load_committed_selection()
    cell = ("a2", 16, 8, 0.01)
    inst = synthetic_instance(seed=16, n_trips=8)
    market = make_affine_market(inst, shape="duck", b_scale=0.01)
    out = str(tmp_path / holdout._cell_tag(cell))
    holdout._commit_cell_provenance(
        out, cell, "commit-a", selection, "a" * 64, inst, market
    )
    with pytest.raises(holdout.HoldoutGuardError, match="mismatch"):
        holdout._commit_cell_provenance(
            out, cell, "commit-b", selection, "a" * 64, inst, market
        )


def test_cell_provenance_refuses_to_adopt_preexisting_checkpoint(tmp_path):
    selection = holdout.load_committed_selection()
    cell = ("a2", 16, 8, 0.01)
    inst = synthetic_instance(seed=16, n_trips=8)
    market = make_affine_market(inst, shape="duck", b_scale=0.01)
    out = tmp_path / holdout._cell_tag(cell)
    out.mkdir()
    stale = out / "a2.cg.ckpt.json"
    stale.write_text('{"done": true}\n')
    with pytest.raises(
        holdout.HoldoutGuardError, match="unprovenanced preexisting"
    ):
        holdout._commit_cell_provenance(
            str(out), cell, "commit-a", selection, "a" * 64, inst, market
        )
    assert stale.exists()
    assert not (out / holdout.CELL_PROVENANCE_FILENAME).exists()


def test_cli_actions_are_strict_and_cell_bounds_checked(monkeypatch):
    ap = holdout._parser()
    with pytest.raises(SystemExit):
        ap.parse_args([])
    with pytest.raises(SystemExit):
        ap.parse_args(["--list", "--all"])
    with pytest.raises(SystemExit):
        holdout.main(["--list", "--mip-gap", "1e-5"])
    monkeypatch.setattr(holdout, "require_execution_context", lambda: "c")
    monkeypatch.setattr(
        holdout, "load_committed_selection",
        lambda: {"selected_arm": "a6_a4"},
    )
    with pytest.raises(SystemExit):
        holdout.main(["--cell", "128"])
    with pytest.raises(SystemExit):
        holdout.main(["--cell", "-1"])


def test_preflight_refuses_non_grb_before_writing(monkeypatch, tmp_path):
    monkeypatch.setattr(holdout, "require_execution_context", lambda: "c")
    monkeypatch.setattr(
        holdout, "load_committed_selection",
        lambda: {"selected_arm": "a6_a4"},
    )
    monkeypatch.setattr(holdout, "backend", lambda: "CBC")

    def must_not_write(*_args, **_kwargs):
        raise AssertionError("preflight evidence must not be written on CBC")

    monkeypatch.setattr(holdout, "write_preflight", must_not_write)
    rc = holdout.main(["--preflight", "--out", str(tmp_path)])
    assert rc == 2
    assert not (tmp_path / holdout.PREFLIGHT_FILENAME).exists()


def test_launcher_and_submit_contracts_are_frozen():
    launch = (holdout.SRC_DIR / "cluster/launch_a6_holdout.sh").read_text()
    submit = (holdout.SRC_DIR / "cluster/submit_a6_holdout.sub").read_text()

    assert launch.index("--preflight") < launch.index("sbatch --parsable")
    assert holdout.EXPECTED_SELECTION_SHA256 in launch
    assert holdout.SELECTION_GATE_COMMIT in launch
    assert '"${BRANCH}" != "main"' in launch
    assert '"${CODE_COMMIT}" != "${ORIGIN_MAIN}"' in launch
    assert "git pull --ff-only origin main" in launch
    assert "METHOD_N" in launch and "expected 64" in launch
    assert "EXPECTED_SEEDS=\"16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31\"" in launch
    assert "forbidden a6_a3" in launch
    assert "--expect-cg 128" in launch
    assert "--expect-cg-method a2=64" in launch
    assert "--expect-cg-method a6_a4=64" in launch
    assert "--expect-cg-certified-method" not in launch
    assert 'CONC=12' in launch
    assert "grid_list_sha256" in launch
    assert "SUBMISSION_LOCK" in launch
    assert "preexisting holdout checkpoint" in launch
    assert launch.index('mkdir "${LOCK_DIR}"') < launch.index("--preflight")
    assert launch.index('mkdir "${LOCK_DIR}"') < launch.index("sbatch --parsable")
    assert 'EGGLAB_HOLDOUT_CODE_COMMIT=${CODE_COMMIT}' in launch

    assert "#SBATCH --array=0-127%12" in submit
    assert "#SBATCH --cpus-per-task=4" in submit
    assert "#SBATCH --mem=8G" in submit
    assert "#SBATCH --time=24:00:00" in submit
    assert "#SBATCH --requeue" in submit
    assert "run_a6_holdout.py" in submit
    assert "runs/a6_holdout" in submit


def test_launcher_functionally_refuses_main_origin_mismatch(tmp_path):
    """Exercise the production shell's unpublished-HEAD refusal without
    reaching Gurobi, feasibility generation, or sbatch."""
    cluster = tmp_path / "repo" / "src" / "cluster"
    cluster.mkdir(parents=True)
    launcher = cluster / "launch_a6_holdout.sh"
    launcher.write_text(
        (holdout.SRC_DIR / "cluster/launch_a6_holdout.sh").read_text()
    )
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    git = fake_bin / "git"
    git.write_text("""#!/bin/sh
case "$*" in
  *"status --porcelain --untracked-files=no"*) exit 0 ;;
  *"symbolic-ref --quiet --short HEAD"*) echo main ;;
  *"rev-parse HEAD"*) echo aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ;;
  *"rev-parse refs/remotes/origin/main"*) echo bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb ;;
  *) echo "unexpected fake git call: $*" >&2; exit 99 ;;
esac
""")
    sbatch = fake_bin / "sbatch"
    sbatch.write_text("#!/bin/sh\necho 'sbatch must not run' >&2\nexit 88\n")
    git.chmod(0o755)
    sbatch.chmod(0o755)
    env = dict(os.environ)
    env["PATH"] = f"{fake_bin}:{env['PATH']}"
    proc = subprocess.run(
        ["bash", str(launcher)], text=True, capture_output=True, env=env
    )
    assert proc.returncode == 1
    assert "!= local origin/main" in proc.stderr
    assert "git pull --ff-only origin main" in proc.stderr
    assert "sbatch must not run" not in proc.stderr


def _fake_happy_launcher_repo(tmp_path):
    """Minimal fake Unicorn/repository contract that reaches sbatch without
    importing project code or generating scientific outcomes."""
    repo = tmp_path / "repo"
    src = repo / "src"
    cluster = src / "cluster"
    experiments = src / "experiments"
    cluster.mkdir(parents=True)
    experiments.mkdir()
    launcher = cluster / "launch_a6_holdout.sh"
    launcher.write_text(
        (holdout.SRC_DIR / "cluster/launch_a6_holdout.sh").read_text()
    )
    (cluster / "unicorn_env.sh").write_text(":\n")

    selection = repo / holdout.SELECTION_RELATIVE_PATH
    selection.parent.mkdir(parents=True)
    selection.write_bytes(
        (holdout.REPO_DIR / holdout.SELECTION_RELATIVE_PATH).read_bytes()
    )
    fake_driver = experiments / "run_a6_holdout.py"
    fake_driver.write_text("""#!/usr/bin/env python3
import json
from pathlib import Path
import sys

if "--preflight" in sys.argv:
    out = Path(sys.argv[sys.argv.index("--out") + 1])
    out.mkdir(parents=True, exist_ok=True)
    (out / "PREFLIGHT.json").write_text(json.dumps({"ok": True}) + "\\n")
elif "--list" in sys.argv:
    print("selection:", {"selected_arm": "a6_a4"})
    k = 0
    for method in ("a2", "a6_a4"):
        for seed in range(16, 32):
            for n in (8, 12):
                for b in (0.01, 0.05):
                    print(k, {"method": method, "seed": seed,
                              "n_trips": n, "b": b,
                              "epsilon": 0.01, "budget": 240})
                    k += 1
    print(f"total: {k} cells")
else:
    raise SystemExit(91)
""")

    fake_bin = tmp_path / "bin"
    fake_bin.mkdir()
    code_commit = "c" * 40
    git = fake_bin / "git"
    git.write_text(f"""#!/bin/sh
case "$*" in
  *"status --porcelain --untracked-files=no"*) exit 0 ;;
  *"symbolic-ref --quiet --short HEAD"*) echo main ;;
  *"rev-parse refs/remotes/origin/main"*) echo {code_commit} ;;
  *"rev-parse HEAD"*) echo {code_commit} ;;
  *"merge-base --is-ancestor"*) exit 0 ;;
  *"ls-files --error-unmatch"*) exit 0 ;;
  *) echo "unexpected fake git call: $*" >&2; exit 99 ;;
esac
""")
    counter = tmp_path / "sbatch.calls"
    sbatch = fake_bin / "sbatch"
    sbatch.write_text("""#!/bin/sh
printf 'call\\n' >> "$FAKE_SBATCH_COUNTER"
echo 424242
""")
    squeue = fake_bin / "squeue"
    squeue.write_text("#!/bin/sh\nexit 0\n")
    for exe in (git, sbatch, squeue):
        exe.chmod(0o755)
    os.symlink(sys.executable, fake_bin / "python")
    env = dict(os.environ)
    env["PATH"] = f"{fake_bin}:{env['PATH']}"
    env["FAKE_SBATCH_COUNTER"] = str(counter)
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    return launcher, src, env, counter


def test_launcher_one_shot_lock_allows_first_and_refuses_second(tmp_path):
    launcher, src, env, counter = _fake_happy_launcher_repo(tmp_path)
    first = subprocess.run(
        ["bash", str(launcher)], cwd=src, text=True,
        capture_output=True, env=env,
    )
    assert first.returncode == 0, first.stderr
    assert counter.read_text().splitlines() == ["call"]
    lock = src / "runs/a6_holdout/SUBMISSION_LOCK"
    assert (lock / "CLAIM.txt").is_file()
    assert (lock / "INTENT.txt").is_file()
    assert (lock / "SUBMITTED.txt").is_file()

    second = subprocess.run(
        ["bash", str(launcher)], cwd=src, text=True,
        capture_output=True, env=env,
    )
    assert second.returncode == 1
    assert "sentinel" in second.stderr
    assert counter.read_text().splitlines() == ["call"]


@pytest.mark.parametrize("checkpoint_name", [
    "a2.cg.ckpt.json", "dictator.ckpt.json",
])
def test_launcher_refuses_preexisting_checkpoint_before_lock_or_sbatch(
    tmp_path, checkpoint_name,
):
    launcher, src, env, counter = _fake_happy_launcher_repo(tmp_path)
    stale = src / f"runs/a6_holdout/a2_s16_n8_b0.01/{checkpoint_name}"
    stale.parent.mkdir(parents=True)
    stale.write_text('{"done": true}\n')
    proc = subprocess.run(
        ["bash", str(launcher)], cwd=src, text=True,
        capture_output=True, env=env,
    )
    assert proc.returncode == 1
    assert "preexisting holdout checkpoint" in proc.stderr
    assert not counter.exists()
    assert not (src / "runs/a6_holdout/SUBMISSION_LOCK").exists()
