"""Build the v0.8 support table from archived v0.7 scalar reconstruction.

No optimizer is imported or run. Public rows combine the independently proved
ideal-model floor with the development screen's conditional native upper.
The depot-15 original-market row also uses the archived exact rational witness.
"""
import json
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "research-20260928/review-response-v07/analytic-bounds/bounds.json"
data = json.loads(DATA.read_text())
rows = data["development_screen_comparison"]
availability_rows = json.loads((ROOT / "research-20260929/charging-availability-bound/bounds.json").read_text())["rows"]
availability = {(row["case"], row["state"]): row for row in availability_rows}
exact_audit = json.loads((ROOT / "research-20260927/agent-notes/exact-public-hull-bound-review/audit-report.json").read_text())
exact_upper = Fraction(exact_audit["separate_exact_witness_nonlinear_upper"]["objective_exact"])

def display_2dp(value, upward):
    cents = -(-100 * value.numerator // value.denominator) if upward else 100 * value.numerator // value.denominator
    return f"{cents // 100}.{cents % 100:02d}"

def interval(values):
    return "$[" + ",".join(values) + "]$"

groups = [
    ("Two-service cyclic", "synthetic_cyclic"),
    ("Three-service visits", "synthetic_multivisit"),
    ("Public depot 15", "public_depot15"),
    ("Public depot 16", "public_depot16"),
]
lines = [r"% Generated by research-20260929/review-response-v08/build_joint_table.py",
 r"\begin{table}[t]", r"\centering\scriptsize", r"\setlength{\tabcolsep}{3pt}",
 r"\caption{Physical and hull cost, gap, and incumbent fixed-price regret in both archived markets. Synthetic rows use conditional native enclosures; the nominal two-service case also has the exact values in Proposition~\ref{prop:exact-nominal}. Public lower endpoints use exact ideal-model charging-availability energy floors; public upper endpoints and regret are conditional on native feasibility and bound tolerances, except for the depot-15 original-market rational witness cap. All intervals are rounded outward. Regret diagnoses the returned planner incumbent, not an optimal public fleet.}",
 r"\label{tab:joint-support}", r"\begin{tabular}{llrrrr}", r"\toprule",
 r"Case & Market & Physical $D$ & Hull $CH$ & Gap $D-CH$ & Regret $r(\hat x)$\\", r"\midrule"]
for label, prefix in groups:
    for state, market in ((0, "Original"), (1, "Changed")):
        row = rows[f"{prefix}_state{state}"]
        bounds = row["mixed_exact_floor_and_native"] if prefix.startswith("public") else row["native_combined"]
        physical = list(bounds["physical_outward_2dp"])
        hull = list(bounds["hull_outward_2dp"])
        gap = list(bounds["gap_outward_2dp"])
        if prefix.startswith("public"):
            floor = Fraction(availability[(prefix, state)]["lower_exact"])
            upper = exact_upper if (prefix, state) == ("public_depot15", 0) else Fraction(bounds["physical_upper_exact"])
            assert upper >= floor
            physical[0] = hull[0] = display_2dp(floor, upward=False)
            physical[1] = hull[1] = display_2dp(upper, upward=True)
            gap[1] = display_2dp(upper - floor, upward=True)
        values = [physical, hull, gap, row["named_planner_incumbent_regret_outward_2dp"]]
        lines.append(label + " & " + market + " & " + " & ".join(map(interval, values)) + r"\\")
    if prefix != groups[-1][1]:
        lines.append(r"\addlinespace")
lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
(ROOT / "paper/latex/joint_support_table.tex").write_text("\n".join(lines) + "\n")
