"""Generate the v0.7 table from read-only reviewed bound reconstruction."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
rows = json.loads((Path(__file__).parent / 'analytic-bounds/bounds.json').read_text())['development_screen_comparison']
labels = [('synthetic_cyclic', 'Two-service cyclic'), ('synthetic_multivisit', 'Three-service visits'), ('public_depot15', 'Public depot 15'), ('public_depot16', 'Public depot 16')]
def interval(values):
    return '$[' + ','.join(values) + ']$'
text = r'''% Generated by research-20260928/review-response-v07/build_joint_table.py
\begin{table}[t]
\centering\small
\setlength{\tabcolsep}{4pt}
\caption{Changed-market support diagnostics from the initial development screen,
with same-screen native bounds combined after the run. All endpoints are rounded
outward. Regret belongs to the returned planner incumbent $\hat x$ in that row;
public planner optima are unknown. Analytical ideal-model energy floors are
reported separately in Table~\ref{tab:analytic-baseline}.}\label{tab:joint-support}
\begin{tabular}{lrrrr}
\toprule
Case & Physical $D$ & Hull $CH$ & Gap $D-CH$ & Regret $r(\hat x)$\\
\midrule
'''
for key, label in labels:
    row = rows[key + '_state1']
    native = row['native_combined']
    vals = [native['physical_outward_2dp'], native['hull_outward_2dp'], native['gap_outward_2dp'], row['named_planner_incumbent_regret_outward_2dp']]
    text += label + ' & ' + ' & '.join(interval(v) for v in vals) + r'\\' + '\n'
text += '\\bottomrule\n\\end{tabular}\n\\end{table}\n'
(ROOT / 'paper/latex/joint_support_table.tex').write_text(text)
